
const $=s=>document.querySelector(s),app=$('#app');
const S={screen:'lobby',game:'hoops',mode:'manual',score:0,best:JSON.parse(localStorage.getItem('arcade-best-v1')||'{}'),remaining:60,shots:0,hits:0,streak:0,longest:0,power:.55,aim:.5,shooting:false,animation:0,clock:0,running:false,paused:false,balls:9,result:'',handTracker:null,video:null,stream:null,cameraRaf:0,pinch:false,tracking:false,cameraError:'',lastHandX:.5,lastHandY:.5,frame:0};
const settings={sound:true,sensitivity:1};
function tone(f=500){if(!settings.sound)return;try{let a=tone.ctx||(tone.ctx=new AudioContext()),o=a.createOscillator(),g=a.createGain();o.type='sine';o.frequency.value=f;g.gain.setValueAtTime(.08,a.currentTime);g.gain.exponentialRampToValueAtTime(.001,a.currentTime+.12);o.connect(g);g.connect(a.destination);o.start();o.stop(a.currentTime+.13)}catch(e){}}
function render(){S.screen==='lobby'?lobby():S.screen==='select'?gameSelection():S.screen==='mode'?mode():S.screen==='camera'?camera():S.screen==='ready'?ready():S.screen==='game'?game():results()}
function nav(x){if(x!=='game'&&x!=='camera')stopGame();if(x==='lobby'||x==='select'||x==='mode')stopCamera();S.screen=x;render()}
function lobby(){app.className='page page-lobby';app.innerHTML=`<section class="landing"><div class="landing-photo"><div class="landing-glass"><span class="small-marker">EST. 2026 / THE INTERNET ARCADE</span><h1>ARCADE<span class="dot">.</span>exe</h1><p>REAL GAMES.<br>REAL MOVES.</p><button id="enter" class="entry-button">GAME ON <span aria-hidden="true">→</span></button></div><span class="landing-footer">YOUR HANDS. REAL GAMES. ANYWHERE.</span></div></section>`;$('#enter').onclick=gameSelection}

function gameSelection(){S.screen='select';app.className='page page-select';app.innerHTML=`<div class="select-layout"><div class="select-head"><div><h1>PICK<br>A GAME</h1><p>TWO CLASSICS. CONTROLLED BY YOU.</p></div><div class="pixels"><b></b><b></b><b></b><b></b></div></div><div class="game-tiles"><button class="game-tile orange" id="hoops"><div class="tile-icon"><svg viewBox="0 0 100 100" aria-hidden="true" class="pixel-icon"><circle cx="50" cy="50" r="38" fill="#171717"/><path d="M50 12v76M12 50h76M23 22Q74 50 23 78M77 22Q26 50 77 78" fill="none" stroke="#f15b40" stroke-width="8"/></svg></div><strong>BASKETBALL</strong><small>SHOOT. SCORE. BEAT YOUR BEST.</small><span class="tile-arrow">→</span></button><button class="game-tile blue" id="skee"><div class="tile-icon"><svg viewBox="0 0 100 100" aria-hidden="true" class="pixel-icon"><rect x="12" y="12" width="76" height="76" rx="3" fill="#151515"/><circle cx="50" cy="50" r="31" stroke="#fff5df" stroke-width="9" fill="none"/><circle cx="50" cy="50" r="14" stroke="#fff5df" stroke-width="8" fill="none"/><circle cx="50" cy="50" r="4" fill="#fff5df"/></svg></div><strong>SKEE-BALL</strong><small>ROLL. SCORE. RACK UP POINTS.</small><span class="tile-arrow">→</span></button></div><div class="selection-footer"><span>YOUR HANDS. REAL GAMES. ANYWHERE.</span><span class="dots">■ ■ ■</span></div></div>`;$('#hoops').onclick=()=>select('hoops');$('#skee').onclick=()=>select('skee')}
function select(g){S.game=g;tone();nav('mode')}
function mode(){app.className='page page-select';app.innerHTML='<section class="setup-choice"><span class="overline">01 / CONTROLS</span><h1>HOW WILL<br>YOU PLAY?</h1><p>CHOOSE YOUR CONTROL METHOD. YOU CAN CHANGE IT LATER.</p><div class="input-choices"><button class="choice" id="hand"><strong>01 / CAMERA</strong><span>MOVE YOUR HAND. PINCH AND RELEASE TO SHOOT.</span><em>→</em></button><button class="choice" id="mouse"><strong>02 / MOUSE + KEYBOARD</strong><span>POINT TO AIM. CLICK OR PRESS SPACE TO THROW.</span><em>→</em></button></div><p class="privacy-inline">Camera frames are processed on this device. Video is never stored or uploaded.</p><button class="back-link" id="back">← BACK TO GAMES</button></section>';$('#hand').onclick=()=>{S.mode='camera';nav('camera')};$('#mouse').onclick=()=>{S.mode='manual';nav('ready')};$('#back').onclick=()=>nav('select')}

function camera(){app.className='page page-camera';app.innerHTML='<section class="camera-layout"><span class="overline">02 / CALIBRATE</span><h1>CAMERA SETUP</h1><p>Use your hand to play. We’ll track your movements.</p><div class="camera-box" id="cam"><span id="camhint">YOUR CAMERA IS OFF. SELECT ENABLE CAMERA TO BEGIN.</span></div><div class="tracking-status" id="track">CAMERA NOT STARTED</div><div class="camera-config"><label>INPUT <span>ONE HAND</span></label><label>MIRROR PREVIEW <input id="mirror" type="checkbox" checked></label></div><div class="camera-actions"><button class="blue-button" id="enable">ENABLE CAMERA</button><button class="blue-button" id="continue" disabled>CONTINUE →</button></div><button class="camera-alternative" id="manual">OR PLAY WITH MOUSE INSTEAD</button><p class="camera-privacy">Your camera is used only to follow your hand. Nothing is recorded or uploaded.</p></section>';$('#enable').onclick=startCamera;$('#continue').onclick=()=>nav('ready');$('#manual').onclick=()=>{S.mode='manual';stopCamera();nav('ready')};$('#mirror').onchange=e=>{if(S.video)S.video.style.transform=e.target.checked?'scaleX(-1)':'none'}}

function trackHand(){if(!S.handTracker||!S.video)return;let lastInference=0,lastFrame=-1,failures=0;const loop=()=>{if(!S.video||!S.handTracker)return;const t=performance.now();if(t-lastInference>=40&&S.video.readyState>=2&&S.video.currentTime!==lastFrame){lastFrame=S.video.currentTime;lastInference=t;try{const r=S.handTracker.detectForVideo(S.video,t),hand=r.landmarks?.[0];S.tracking=!!hand;failures=0;if(hand){const thumb=hand[4],index=hand[8],palm=hand[9],sideA=hand[5],sideB=hand[17];const width=Math.hypot(sideA.x-sideB.x,sideA.y-sideB.y)||.1;const d=Math.hypot(thumb.x-index.x,thumb.y-index.y)/width;const was=S.pinch;S.pinch=d<(was?.53:.32);S.aim=Math.max(.05,Math.min(.95,1-palm.x));S.power=Math.max(.12,Math.min(.95,1-palm.y));S.lastHandX=palm.x;S.lastHandY=palm.y;if(was&&!S.pinch&&S.screen==='game'&&!S.paused)shoot();const status=$('#track');if(status)status.textContent='HAND DETECTED · '+(S.pinch?'PINCHED':'OPEN')}else{S.pinch=false;const status=$('#track');if(status)status.textContent='LOOKING FOR HAND · MOVE INTO FRAME'}}catch(e){failures++;console.error('Hand tracking error',e);if(failures>=3){const status=$('#track');if(status)status.textContent='TRACKING INTERRUPTED · TRY MOUSE MODE';S.tracking=false}}}S.cameraRaf=requestAnimationFrame(loop)};S.cameraRaf=requestAnimationFrame(loop)}
function stopCamera(){cancelAnimationFrame(S.cameraRaf);S.cameraRaf=0;S.handTracker?.close?.();S.handTracker=null;S.video=null;S.stream?.getTracks().forEach(t=>t.stop());S.stream=null;S.tracking=false}
function ready(){app.className='page page-ready';app.innerHTML='<section class="ready-layout"><span class="overline">03 / READY TO PLAY</span><h1>'+(S.game==='hoops'?'BASKETBALL':'SKEE-BALL')+'</h1><div class="ready-graphic">'+(S.game==='hoops'?"<svg viewBox=\"0 0 100 100\" aria-hidden=\"true\" class=\"pixel-icon\"><circle cx=\"50\" cy=\"50\" r=\"38\" fill=\"#171717\"/><path d=\"M50 12v76M12 50h76M23 22Q74 50 23 78M77 22Q26 50 77 78\" fill=\"none\" stroke=\"#f15b40\" stroke-width=\"8\"/></svg>":"<svg viewBox=\"0 0 100 100\" aria-hidden=\"true\" class=\"pixel-icon\"><rect x=\"12\" y=\"12\" width=\"76\" height=\"76\" rx=\"3\" fill=\"#151515\"/><circle cx=\"50\" cy=\"50\" r=\"31\" stroke=\"#fff5df\" stroke-width=\"9\" fill=\"none\"/><circle cx=\"50\" cy=\"50\" r=\"14\" stroke=\"#fff5df\" stroke-width=\"8\" fill=\"none\"/><circle cx=\"50\" cy=\"50\" r=\"4\" fill=\"#fff5df\"/></svg>")+'</div><h2>'+(S.game==='hoops'?'60 SECONDS. UNLIMITED SHOTS.':'9 BALLS. MAKE THEM COUNT.')+'</h2><p>'+(S.mode==='camera'?'MOVE YOUR HAND TO AIM. PINCH AND OPEN YOUR FINGERS TO RELEASE.':'MOVE YOUR POINTER TO AIM AND CONTROL POWER. CLICK OR PRESS SPACE TO LAUNCH.')+'</p><button class="dark-button" id="begin">START GAME →</button><button class="back-link" id="back">← CHANGE CONTROLS</button></section>';$('#begin').onclick=()=>{reset();nav('game')};$('#back').onclick=()=>nav('mode')}

function reset(){stopGame();S.score=0;S.remaining=60;S.balls=9;S.shots=0;S.hits=0;S.streak=0;S.longest=0;S.shooting=false;S.paused=false;S.result='';S.power=.55;S.aim=.5}
let ctx,canvas,last=0,raf=0,clockInterval=0,shots=[];
function stopGame(){S.running=false;cancelAnimationFrame(raf);clearInterval(clockInterval);shots=[]}
function game(){app.className='page page-game';app.innerHTML='<div class="editorial-game"><div class="editorial-hud"><div class="hud-title"><span class="overline">NOW PLAYING</span><h1>'+(S.game==='hoops'?'BASKETBALL':'SKEE-BALL')+'</h1></div><div class="hud-stats"><div><label>'+(S.game==='hoops'?'TIME':'BALLS LEFT')+'</label><strong id="time">'+(S.game==='hoops'?'60':'9')+'</strong></div><div><label>SCORE</label><strong id="score">0</strong></div><div class="hud-third"><label>'+(S.game==='hoops'?'STREAK':'BEST')+'</label><strong id="third">'+(S.game==='hoops'?'0':S.best.skee||0)+'</strong></div></div><button class="end-game" id="exit">END GAME</button></div><div class="stage"><canvas id="canvas" width="1000" height="562" aria-label="Game playfield"></canvas><div id="gamecam"></div></div><div class="game-controls"><p id="gamehint">MOVE TO AIM · CLICK OR SPACE TO THROW · P TO PAUSE</p><button id="pause">PAUSE</button><label>POWER <span class="meter"><span class="meter-fill" id="power"></span></span></label></div></div>';canvas=$('#canvas');ctx=canvas.getContext('2d');canvas.addEventListener('pointermove',e=>{if(S.mode==='camera'&&S.tracking)return;let b=canvas.getBoundingClientRect();S.aim=Math.max(.05,Math.min(.95,(e.clientX-b.left)/b.width));S.power=Math.max(.15,Math.min(.95,1-(e.clientY-b.top)/b.height))});canvas.addEventListener('pointerdown',()=>{if(!S.paused)shoot()});$('#pause').onclick=pause;$('#exit').onclick=()=>nav('lobby');if(S.mode==='camera'&&S.video){let v=S.video;v.remove();v.style.cssText='';$('#gamecam').append(v)}S.running=true;last=performance.now();raf=requestAnimationFrame(draw);if(S.game==='hoops')clockInterval=setInterval(()=>{if(S.paused||!S.running)return;S.remaining=Math.max(0,S.remaining-1);if(S.remaining===0){S.running=false;setTimeout(()=>finish(),1000)}update()},1000)}
function update(){let el=$('#score');if(!el)return;el.textContent=S.score;$('#time').textContent=S.game==='hoops'?S.remaining:S.balls;$('#third').textContent=S.game==='hoops'?S.streak:(S.best.skee||0);$('#power').style.width=(S.power*100)+'%'}
function draw(now){if(!S.running)return;let dt=Math.min((now-last)/1000,.06);last=now;if(!S.paused){try{renderStage(dt);update()}catch(err){console.error('Game rendering error',err);S.running=false;const e=$('#gamehint');if(e)e.textContent='GAME ERROR: '+err.message+' — USE END GAME TO RETURN';return}}raf=requestAnimationFrame(draw)}
function renderStage(dt){let w=1000,h=562;ctx.clearRect(0,0,w,h);let grad=ctx.createLinearGradient(0,0,0,h);grad.addColorStop(0,'#35263f');grad.addColorStop(1,'#161824');ctx.fillStyle=grad;ctx.fillRect(0,0,w,h);ctx.globalAlpha=.25;for(let i=0;i<20;i++){ctx.fillStyle='#ffde9c';ctx.beginPath();ctx.arc((i*73+22)%1000,55+(i*37)%225,2,0,7);ctx.fill()}ctx.globalAlpha=1;if(S.game==='hoops')renderHoops();else renderSkee();for(let i=shots.length-1;i>=0;i--){let s=shots[i];s.t+=dt;let p=s.t/s.d;let x=s.x+(s.targetX-s.x)*p;let y=s.y+(s.targetY-s.y)*p-180*Math.sin(Math.PI*p);ctx.fillStyle=S.game==='hoops'?'#eb8c43':'#eee6d6';ctx.beginPath();ctx.arc(x,y,20*(1-Math.max(0,p-1)*.7),0,7);ctx.fill();if(S.game==='hoops'){ctx.strokeStyle='#853b23';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(x-12,y-12);ctx.lineTo(x+12,y+12);ctx.moveTo(x-12,y+12);ctx.lineTo(x+12,y-12);ctx.stroke()}if(p>=1){resolve(s);shots.splice(i,1)}}let x=100+S.aim*800;ctx.strokeStyle='#f2be57bb';ctx.setLineDash([6,10]);ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(x,h-56);ctx.lineTo(S.game==='hoops'?500:500,S.game==='hoops'?195:195);ctx.stroke();ctx.setLineDash([]);ctx.fillStyle='#f2be57';ctx.beginPath();ctx.arc(x,h-52,23,0,7);ctx.fill();ctx.fillStyle='#612f2a';ctx.font='30px sans-serif';ctx.textAlign='center';ctx.fillText(S.game==='hoops'?'●':'◉',x+1,h-43);ctx.fillStyle='#f7e8c6';ctx.font='bold 15px "DM Sans"';ctx.fillText(S.result,500,65)}
function renderHoops(){ctx.fillStyle='#74494b';ctx.fillRect(0,470,1000,92);ctx.strokeStyle='#e4a76d';ctx.lineWidth=6;ctx.beginPath();ctx.moveTo(0,470);ctx.lineTo(1000,470);ctx.stroke();ctx.fillStyle='#f7e8c6';ctx.fillRect(420,110,160,120);ctx.strokeStyle='#aa463c';ctx.lineWidth=12;ctx.strokeRect(420,110,160,120);ctx.strokeStyle='#f3a15b';ctx.lineWidth=12;ctx.beginPath();ctx.ellipse(500,234,65,17,0,0,Math.PI*2);ctx.stroke();ctx.strokeStyle='#e2cab5';ctx.lineWidth=2;for(let i=-4;i<=4;i++){ctx.beginPath();ctx.moveTo(500+i*13,249);ctx.lineTo(500+i*10,318);ctx.stroke()}ctx.fillStyle='#c99d61';ctx.font='bold 18px "DM Sans"';ctx.textAlign='center';ctx.fillText('SWISH FOR +3',500,92)}
function renderSkee(){
const w=1000,h=562;
const bg=ctx.createLinearGradient(0,30,0,h);bg.addColorStop(0,'#162732');bg.addColorStop(.48,'#234954');bg.addColorStop(1,'#12212a');ctx.fillStyle=bg;ctx.fillRect(0,0,w,h);
ctx.fillStyle='#0c1720';ctx.fillRect(0,65,w,155);
for(let k=0;k<11;k++){let z=k/11;let left=315-z*170,right=685+z*170,y=210+z*350;ctx.strokeStyle=k%2?'#365461':'#59707a';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(left,y);ctx.lineTo(right,y);ctx.stroke()}
const lane=ctx.createLinearGradient(0,190,0,562);lane.addColorStop(0,'#cb9d68');lane.addColorStop(.55,'#b78150');lane.addColorStop(1,'#dbaf77');ctx.fillStyle=lane;ctx.beginPath();ctx.moveTo(338,198);ctx.lineTo(662,198);ctx.lineTo(855,562);ctx.lineTo(145,562);ctx.closePath();ctx.fill();
for(let i=0;i<20;i++){let xx=155+i*36;ctx.strokeStyle=i%3?'#70482c36':'#f4d5a04d';ctx.lineWidth=i%4===0?2:1;ctx.beginPath();ctx.moveTo(500+(xx-500)*.44,210);ctx.lineTo(xx,562);ctx.stroke()}
ctx.fillStyle='#e5b34e';ctx.beginPath();ctx.moveTo(145,562);ctx.lineTo(325,192);ctx.lineTo(344,192);ctx.lineTo(173,562);ctx.closePath();ctx.fill();ctx.beginPath();ctx.moveTo(827,562);ctx.lineTo(656,192);ctx.lineTo(675,192);ctx.lineTo(855,562);ctx.closePath();ctx.fill();
ctx.fillStyle='#123b48';ctx.beginPath();ctx.moveTo(312,198);ctx.lineTo(344,200);ctx.lineTo(173,562);ctx.lineTo(131,562);ctx.closePath();ctx.fill();ctx.beginPath();ctx.moveTo(688,198);ctx.lineTo(656,200);ctx.lineTo(827,562);ctx.lineTo(869,562);ctx.closePath();ctx.fill();
ctx.fillStyle='#0b2230';ctx.fillRect(265,55,470,172);ctx.strokeStyle='#d49a5d';ctx.lineWidth=7;ctx.strokeRect(265,55,470,172);
const zones=[[356,105,100],[644,105,100],[500,95,50],[500,135,40],[500,175,30],[427,181,20],[573,181,20]];
zones.forEach(([x,y,p])=>{const r=p===100?27:25;ctx.shadowColor='#0009';ctx.shadowBlur=12;ctx.shadowOffsetY=7;ctx.beginPath();ctx.arc(x,y+5,r+5,0,7);ctx.fillStyle='#081923';ctx.fill();ctx.shadowBlur=0;ctx.shadowOffsetY=0;ctx.lineWidth=9;ctx.strokeStyle=p===100?'#eab551':'#f2e2bd';ctx.beginPath();ctx.arc(x,y,r,0,7);ctx.stroke();ctx.fillStyle='#f5ead4';ctx.font='800 18px DM Sans';ctx.textAlign='center';ctx.fillText(p,x,y+6)});
ctx.fillStyle='#e9bb70';ctx.fillRect(297,223,406,10);
ctx.fillStyle='#f4ebd9';ctx.font='700 16px DM Sans';ctx.textAlign='center';ctx.fillText('ROLL WITH IT',500,35);
}
function shoot(){if(!S.running||S.paused||S.remaining===0&&S.game==='hoops'||S.game==='skee'&&S.balls===0)return;S.shots++;if(S.game==='skee')S.balls--;let accuracy=Math.abs(S.aim-.5);let shot={x:100+800*S.aim,y:505,targetX:500+(S.aim-.5)*460,targetY:S.game==='hoops'?228:110+Math.round((1-S.power)*90),t:0,d:.55+(1-S.power)*.35,accuracy,power:S.power};shots.push(shot);S.result='SHOT AWAY!';tone(285);update()}
function resolve(s){if(S.game==='hoops'){let made=s.accuracy<(.095+s.power*.13)&&s.power>.28;if(made){let swish=s.accuracy<.075;S.streak++;S.longest=Math.max(S.longest,S.streak);let pts=(swish?3:2)*(S.streak>=3?2:1);S.score+=pts;S.hits++;S.result=swish?'SWISH! +'+pts:'BUCKET! +'+pts;tone(740)}else{S.streak=0;S.result='SO CLOSE!';tone(195)}}else{let a=s.accuracy,p=s.power;let pts=p<.22?0:a<.07&&p>.77?50:a>.3&&p>.7?100:a<.12?40:a<.22?30:a<.32?20:10;S.score+=pts;if(pts)S.hits++;S.result=pts?('+'+pts+' POINTS!'):'ROLLED SHORT';tone(pts>=50?780:450);if(S.balls===0&&shots.length<=1)setTimeout(finish,900)}update()}
function finish(){if(S.screen!=='game')return;stopGame();let prev=S.best[S.game]||0;S.newBest=S.score>prev;if(S.newBest){S.best[S.game]=S.score;localStorage.setItem('arcade-best-v1',JSON.stringify(S.best))}stopCamera();nav('results')}
function results(){app.className='page page-results';let accuracy=S.shots?Math.round(S.hits/S.shots*100):0;app.innerHTML='<section class="results-layout"><span class="overline">ROUND COMPLETE</span><h1>YOUR SCORE</h1><div class="score-ticket"><div class="ticket-avatar">A.</div><div class="ticket-text"><strong>'+(S.game==='hoops'?'BASKETBALL':'SKEE-BALL')+'</strong><small>SCORE</small><div class="ticket-number">'+S.score+'</div></div><div class="ticket-barcode"></div><div class="ticket-best">'+(S.newBest?'NEW PERSONAL BEST!':'PERSONAL BEST: '+(S.best[S.game]||0))+'</div></div><div class="result-stats"><div><span>ATTEMPTS</span><strong>'+S.shots+'</strong></div><div><span>SUCCESSFUL</span><strong>'+S.hits+'</strong></div><div><span>ACCURACY</span><strong>'+accuracy+'%</strong></div><div><span>'+(S.game==='hoops'?'BEST STREAK':'BALLS USED')+'</span><strong>'+(S.game==='hoops'?S.longest:S.shots)+'</strong></div></div><div class="result-actions"><button class="dark-button" id="again">PLAY AGAIN</button><button class="outline-button" id="change">BACK TO LOBBY</button><button class="outline-button" id="share">SHARE SCORE</button></div></section>';$('#again').onclick=()=>nav('mode');$('#change').onclick=()=>nav('lobby');$('#share').onclick=async()=>{let msg='I scored '+S.score+' in '+(S.game==='hoops'?'Basketball':'Skee-ball')+' on ARCADE.exe';try{if(navigator.share)await navigator.share({title:'ARCADE.exe',text:msg,url:location.href});else{await navigator.clipboard.writeText(msg+' '+location.href);alert('Score copied')}}catch(e){}}}

function pause(){if(S.screen!=='game')return;S.paused=!S.paused;const btn=$('#pause');if(btn){btn.textContent=S.paused?'RESUME':'PAUSE';btn.setAttribute('aria-pressed',String(S.paused))}const hint=$('#gamehint');if(hint)hint.textContent=S.paused?'GAME PAUSED — PRESS RESUME OR P':'MOVE TO AIM · CLICK OR SPACE TO THROW · P TO PAUSE';const stage=$('.stage');let overlay=$('#pause-overlay');if(S.paused&&stage){if(!overlay){overlay=document.createElement('div');overlay.id='pause-overlay';overlay.style.cssText='position:absolute;inset:0;z-index:8;display:grid;place-content:center;text-align:center;gap:18px;background:rgba(10,15,23,.77);color:#fff';overlay.innerHTML='<h2 style="font:900 36px Archivo Black;margin:0">GAME PAUSED</h2><p style="margin:0">Your round is safe. Press Resume to keep playing.</p><button type="button" id="resume-overlay" style="background:#f5f0e6;color:#171717;padding:14px 35px;border:0;font-weight:900;cursor:pointer">RESUME GAME</button>';stage.append(overlay);overlay.querySelector('button').onclick=pause}}else if(overlay)overlay.remove()}
function openSettings(){let d=document.createElement('div');d.className='modal-bg';d.innerHTML='<section class="editorial-modal"><button id="done" class="modal-close">← BACK</button><h1>SETTINGS</h1><h3>AUDIO</h3><label>Sound effects <input type="range" min="0" max="1" step="1" id="sound" value="'+(settings.sound?1:0)+'"></label><h3>GAMEPLAY</h3><label>Input sensitivity <input type="range" min=".5" max="1.8" step=".1" id="sens" value="'+settings.sensitivity+'"></label><h3>VISUAL</h3><label>Reduced motion <input type="checkbox" id="reduced"></label></section>';document.body.append(d);d.querySelector('#sound').oninput=e=>settings.sound=+e.target.value>0;d.querySelector('#sens').oninput=e=>settings.sensitivity=+e.target.value;d.querySelector('#done').onclick=()=>d.remove();d.onclick=e=>{if(e.target===d)d.remove()}}

$('#home').onclick=()=>nav('lobby');$('#settings').onclick=openSettings;$('#help').onclick=()=>alert('Pick a game, choose webcam or mouse, aim using your hand or pointer, then pinch-release or click/Space to throw. P pauses the round.');
document.addEventListener('keydown',e=>{if(e.code==='Escape'&&S.screen==='game')pause();if(e.code==='KeyP'&&S.screen==='game')pause();if(e.code==='Space'&&S.screen==='game'){e.preventDefault();shoot()}if(S.screen==='game'&&!S.paused){if(e.code==='ArrowLeft')S.aim=Math.max(.05,S.aim-.045*settings.sensitivity);if(e.code==='ArrowRight')S.aim=Math.min(.95,S.aim+.045*settings.sensitivity);if(e.code==='ArrowUp')S.power=Math.min(.95,S.power+.05*settings.sensitivity);if(e.code==='ArrowDown')S.power=Math.max(.15,S.power-.05*settings.sensitivity)}});
document.addEventListener('visibilitychange',()=>{if(document.hidden&&S.screen==='game'&&!S.paused)pause()});window.addEventListener('beforeunload',stopCamera);render();
