import {Arcade3D} from './arcade3d.js';

const $=s=>document.querySelector(s),app=$('#app');
let world3d=null;
const S={screen:'lobby',game:'hoops',mode:'manual',score:0,best:JSON.parse(localStorage.getItem('arcade-best-v1')||'{}'),remaining:60,shots:0,hits:0,streak:0,longest:0,power:.55,aim:.5,shooting:false,animation:0,clock:0,running:false,paused:false,balls:9,result:'',handTracker:null,video:null,stream:null,cameraRaf:0,pinch:false,tracking:false,cameraError:'',lastHandX:.5,lastHandY:.5,frame:0};
const settings={sound:true,sensitivity:1};

// Hand-controlled arcade input, version 5: calibrated pinch hold and inertial release.
const G={phase:'idle',history:[],hold:null,lastVideoTime:-1,missedAt:0,cooldown:0,gestureFrame:0,seenPinch:false,releaseFrames:0,screenX:500,screenY:460,confidence:0};
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
function handFrame(hand,t){const palm=hand[9],a=hand[5],b=hand[17],thumb=hand[4],tip=hand[8];const width=Math.max(.035,Math.hypot(a.x-b.x,a.y-b.y));const d=Math.hypot(thumb.x-tip.x,thumb.y-tip.y)/width;const x=clamp(1-(palm.x-.08)/.84,0,1),y=clamp((palm.y-.12)/.76,0,1);G.screenX=100+800*x;G.screenY=clamp(110+410*y,110,515);S.aim=x;const previous=G.history[G.history.length-1];const smooth=previous?{x:previous.x*.52+x*.48,y:previous.y*.52+y*.48,t}: {x,y,t};G.history.push(smooth);while(G.history.length&&t-G.history[0].t>210)G.history.shift();S.power=clamp(.28+(1-y)*.58,.2,.92);return d}
function releaseVector(){const last=G.history[G.history.length-1],first=[...G.history].reverse().find(p=>last.t-p.t>=75)||G.history[0];const sec=Math.max(.06,(last.t-first.t)/1000);return {x:clamp((last.x-first.x)/sec,-3,3),y:clamp((last.y-first.y)/sec,-3,3)}}
function armBall(){if(!S.running||S.paused||G.phase!=='idle'||performance.now()<G.cooldown)return;G.phase='holding';G.hold={x:G.screenX,y:G.screenY};S.result='HOLDING · OPEN TO THROW';tone(380)}
function releaseBall(){if(G.phase!=='holding'||!S.running||S.paused)return;const v=releaseVector();G.phase='cooldown';G.cooldown=performance.now()+490;S.aim=clamp((G.screenX-100)/800,.05,.95);S.power=clamp(.43+Math.max(0,-v.y)*.14,.3,.96);shoot({vx:v.x,vy:v.y,startX:G.screenX,startY:G.screenY,hand:true});G.history.length=0;G.seenPinch=false}

function tone(f=500){if(!settings.sound)return;try{let a=tone.ctx||(tone.ctx=new AudioContext()),o=a.createOscillator(),g=a.createGain();o.type='sine';o.frequency.value=f;g.gain.setValueAtTime(.08,a.currentTime);g.gain.exponentialRampToValueAtTime(.001,a.currentTime+.12);o.connect(g);g.connect(a.destination);o.start();o.stop(a.currentTime+.13)}catch(e){}}
function render(){S.screen==='lobby'?lobby():S.screen==='select'?gameSelection():S.screen==='mode'?mode():S.screen==='camera'?camera():S.screen==='ready'?ready():S.screen==='game'?game():results()}
function nav(x){if(x!=='game'&&x!=='camera')stopGame();if(x==='lobby'||x==='select'||x==='mode')stopCamera();S.screen=x;render()}
function lobby(){app.className='page page-lobby';app.innerHTML=`<section class="landing"><div class="landing-photo"><div class="landing-glass"><span class="small-marker">EST. 2026 / THE INTERNET ARCADE</span><h1>ARCADE<span class="dot">.</span>exe</h1><p>REAL GAMES.<br>REAL MOVES.</p><button id="enter" class="entry-button">GAME ON <span aria-hidden="true">→</span></button></div><span class="landing-footer">YOUR HANDS. REAL GAMES. ANYWHERE.</span></div></section>`;$('#enter').onclick=gameSelection}

function gameSelection(){S.screen='select';app.className='page page-select';app.innerHTML=`<div class="select-layout"><div class="select-head"><div><h1>PICK<br>A GAME</h1><p>TWO CLASSICS. CONTROLLED BY YOU.</p></div><div class="pixels"><b></b><b></b><b></b><b></b></div></div><div class="game-tiles"><button class="game-tile orange" id="hoops"><div class="tile-icon"><svg viewBox="0 0 100 100" aria-hidden="true" class="pixel-icon"><circle cx="50" cy="50" r="38" fill="#171717"/><path d="M50 12v76M12 50h76M23 22Q74 50 23 78M77 22Q26 50 77 78" fill="none" stroke="#f15b40" stroke-width="8"/></svg></div><strong>BASKETBALL</strong><small>SHOOT. SCORE. BEAT YOUR BEST.</small><span class="tile-arrow">→</span></button><button class="game-tile blue" id="skee"><div class="tile-icon"><svg viewBox="0 0 100 100" aria-hidden="true" class="pixel-icon"><rect x="12" y="12" width="76" height="76" rx="3" fill="#151515"/><circle cx="50" cy="50" r="31" stroke="#fff5df" stroke-width="9" fill="none"/><circle cx="50" cy="50" r="14" stroke="#fff5df" stroke-width="8" fill="none"/><circle cx="50" cy="50" r="4" fill="#fff5df"/></svg></div><strong>SKEE-BALL</strong><small>ROLL. SCORE. RACK UP POINTS.</small><span class="tile-arrow">→</span></button></div><div class="selection-footer"><span>YOUR HANDS. REAL GAMES. ANYWHERE.</span><span class="dots">■ ■ ■</span></div></div>`;$('#hoops').onclick=()=>select('hoops');$('#skee').onclick=()=>select('skee')}
function select(g){S.game=g;tone();nav('mode')}
function mode(){app.className='page page-select';app.innerHTML='<section class="setup-choice"><span class="overline">01 / CONTROLS</span><h1>HOW WILL<br>YOU PLAY?</h1><p>CHOOSE YOUR CONTROL METHOD. YOU CAN CHANGE IT LATER.</p><div class="input-choices"><button class="choice" id="hand"><strong>01 / CAMERA</strong><span>MOVE YOUR HAND. PINCH AND RELEASE TO SHOOT.</span><em>→</em></button><button class="choice" id="mouse"><strong>02 / MOUSE + KEYBOARD</strong><span>POINT TO AIM. CLICK OR PRESS SPACE TO THROW.</span><em>→</em></button></div><p class="privacy-inline">Camera frames are processed on this device. Video is never stored or uploaded.</p><button class="back-link" id="back">← BACK TO GAMES</button></section>';$('#hand').onclick=()=>{S.mode='camera';nav('camera')};$('#mouse').onclick=()=>{S.mode='manual';nav('ready')};$('#back').onclick=()=>nav('select')}

function camera(){app.className='page page-camera';app.innerHTML='<section class="camera-layout"><span class="overline">02 / CALIBRATE</span><h1>CAMERA SETUP</h1><p>Use your hand to play. We’ll track your movements.</p><div class="camera-box" id="cam"><span id="camhint">YOUR CAMERA IS OFF. SELECT ENABLE CAMERA TO BEGIN.</span></div><div class="tracking-status" id="track">CAMERA NOT STARTED</div><div class="camera-config"><label>INPUT <span>ONE HAND</span></label><label>MIRROR PREVIEW <input id="mirror" type="checkbox" checked></label></div><div class="camera-actions"><button class="blue-button" id="enable">ENABLE CAMERA</button><button class="blue-button" id="continue" disabled>CONTINUE →</button></div><button class="camera-alternative" id="manual">OR PLAY WITH MOUSE INSTEAD</button><p class="camera-privacy">Your camera is used only to follow your hand. Nothing is recorded or uploaded.</p></section>';$('#enable').onclick=startCamera;$('#continue').onclick=()=>nav('ready');$('#manual').onclick=()=>{S.mode='manual';stopCamera();nav('ready')};$('#mirror').onchange=e=>{if(S.video)S.video.style.transform=e.target.checked?'scaleX(-1)':'none'}}

function trackHand(){if(!S.handTracker||!S.video)return;const loop=()=>{if(!S.video||!S.handTracker)return;try{if(S.video.readyState>=2&&S.video.currentTime!==G.lastVideoTime){G.lastVideoTime=S.video.currentTime;const t=performance.now();const r=S.handTracker.detectForVideo(S.video,t),hand=r.landmarks?.[0];S.tracking=!!hand;if(hand){G.missedAt=0;const d=handFrame(hand,t),pinch=G.phase==='holding'?d<.54:d<.33;S.pinch=pinch;if(G.phase==='cooldown'&&t>G.cooldown)G.phase='idle';if(G.phase==='idle'){G.gestureFrame=pinch?G.gestureFrame+1:0;if(G.gestureFrame>=2){armBall();G.gestureFrame=0}}else if(G.phase==='holding'){G.hold={x:G.screenX,y:G.screenY};G.releaseFrames=pinch?0:G.releaseFrames+1;if(G.releaseFrames>=2){G.releaseFrames=0;releaseBall()}}let status=$('#track');if(status)status.textContent=G.phase==='holding'?'HAND DETECTED · BALL HELD · OPEN TO RELEASE':'HAND DETECTED · PINCH TO PICK UP'}else{S.pinch=false;G.history.length=0;if(G.phase==='holding'){if(!G.missedAt)G.missedAt=t;if(t-G.missedAt>350){G.phase='cooldown';G.cooldown=t+500;S.result='TRACKING LOST · BALL RETURNED'}}let status=$('#track');if(status)status.textContent='LOOKING FOR HAND · MOVE INTO FRAME'}}}catch(e){let status=$('#track');if(status)status.textContent='HAND TRACKING INTERRUPTED · '+e.message}S.cameraRaf=requestAnimationFrame(loop)};S.cameraRaf=requestAnimationFrame(loop)}

function stopCamera(){cancelAnimationFrame(S.cameraRaf);S.cameraRaf=0;S.handTracker?.close?.();S.handTracker=null;S.video=null;S.stream?.getTracks().forEach(t=>t.stop());S.stream=null;S.tracking=false}
function ready(){app.className='page page-ready';app.innerHTML='<section class="ready-layout"><span class="overline">03 / READY TO PLAY</span><h1>'+(S.game==='hoops'?'BASKETBALL':'SKEE-BALL')+'</h1><div class="ready-graphic">'+(S.game==='hoops'?"<svg viewBox=\"0 0 100 100\" aria-hidden=\"true\" class=\"pixel-icon\"><circle cx=\"50\" cy=\"50\" r=\"38\" fill=\"#171717\"/><path d=\"M50 12v76M12 50h76M23 22Q74 50 23 78M77 22Q26 50 77 78\" fill=\"none\" stroke=\"#f15b40\" stroke-width=\"8\"/></svg>":"<svg viewBox=\"0 0 100 100\" aria-hidden=\"true\" class=\"pixel-icon\"><rect x=\"12\" y=\"12\" width=\"76\" height=\"76\" rx=\"3\" fill=\"#151515\"/><circle cx=\"50\" cy=\"50\" r=\"31\" stroke=\"#fff5df\" stroke-width=\"9\" fill=\"none\"/><circle cx=\"50\" cy=\"50\" r=\"14\" stroke=\"#fff5df\" stroke-width=\"8\" fill=\"none\"/><circle cx=\"50\" cy=\"50\" r=\"4\" fill=\"#fff5df\"/></svg>")+'</div><h2>'+(S.game==='hoops'?'60 SECONDS. UNLIMITED SHOTS.':'9 BALLS. MAKE THEM COUNT.')+'</h2><p>'+(S.mode==='camera'?'MOVE YOUR HAND TO AIM. PINCH AND OPEN YOUR FINGERS TO RELEASE.':'MOVE YOUR POINTER TO AIM AND CONTROL POWER. CLICK OR PRESS SPACE TO LAUNCH.')+'</p><button class="dark-button" id="begin">START GAME →</button><button class="back-link" id="back">← CHANGE CONTROLS</button></section>';$('#begin').onclick=()=>{reset();nav('game')};$('#back').onclick=()=>nav('mode')}

function reset(){stopGame();G.phase='idle';G.history.length=0;G.cooldown=0;G.gestureFrame=0;G.hold=null;G.releaseFrames=0;S.score=0;S.remaining=60;S.balls=9;S.shots=0;S.hits=0;S.streak=0;S.longest=0;S.shooting=false;S.paused=false;S.result='';S.power=.55;S.aim=.5}

function stopGame(){S.running=false;cancelAnimationFrame(raf);clearInterval(clockInterval);shots=[];world3d?.dispose();world3d=null}
function game(){app.className='page page-game';app.innerHTML='<div class="editorial-game"><div class="editorial-hud"><div class="hud-title"><span class="overline">NOW PLAYING</span><h1>'+(S.game==='hoops'?'BASKETBALL':'SKEE-BALL')+'</h1></div><div class="hud-stats"><div><label>'+(S.game==='hoops'?'TIME':'BALLS LEFT')+'</label><strong id="time">'+(S.game==='hoops'?'60':'9')+'</strong></div><div><label>SCORE</label><strong id="score">0</strong></div><div class="hud-third"><label>'+(S.game==='hoops'?'STREAK':'BEST')+'</label><strong id="third">'+(S.game==='hoops'?'0':S.best.skee||0)+'</strong></div></div><button class="end-game" id="exit">END GAME</button></div><div class="stage"><canvas id="canvas" width="1000" height="562" aria-label="Game playfield"></canvas><div id="gamecam"></div></div><div class="game-controls"><p id="gamehint">MOVE TO AIM · CLICK OR SPACE TO THROW · P TO PAUSE</p><button id="pause">PAUSE</button><label>POWER <span class="meter"><span class="meter-fill" id="power"></span></span></label></div></div>';canvas=$('#canvas');try{world3d=new Arcade3D(canvas,S.game,(result,shot)=>{const scored={hit:result.hit,wall:!result.swish,scored:false};resolve(scored)});canvas.addEventListener('webglcontextlost',e=>{e.preventDefault();showGameError('Graphics context was lost. Try restarting the round.')})}catch(err){console.error('3D initialization failed:',err);showGameError('3D graphics could not start on this browser. '+err.message);return}canvas.addEventListener('pointermove',e=>{if(S.mode==='camera'&&S.tracking)return;let b=canvas.getBoundingClientRect();S.aim=Math.max(.05,Math.min(.95,(e.clientX-b.left)/b.width));S.power=Math.max(.15,Math.min(.95,1-(e.clientY-b.top)/b.height))});canvas.addEventListener('pointerdown',e=>{if(S.paused||S.mode==='camera'&&S.tracking)return;S.manualDown={x:e.clientX,y:e.clientY,t:performance.now()};canvas.setPointerCapture(e.pointerId)});canvas.addEventListener('pointerup',e=>{if(!S.manualDown||S.paused)return;let b=canvas.getBoundingClientRect(),dx=(e.clientX-S.manualDown.x)/b.width,dy=(e.clientY-S.manualDown.y)/b.height,elapsed=Math.max(.12,(performance.now()-S.manualDown.t)/1000);S.manualDown=null;shoot({vx:dx/elapsed,vy:dy/elapsed})});$('#pause').onclick=pause;$('#exit').onclick=()=>nav('lobby');if(S.mode==='camera'&&S.video){let v=S.video;v.remove();v.style.cssText='';$('#gamecam').append(v)}S.running=true;last=performance.now();raf=requestAnimationFrame(draw);if(S.game==='hoops')clockInterval=setInterval(()=>{if(S.paused||!S.running)return;S.remaining=Math.max(0,S.remaining-1);if(S.remaining===0){S.running=false;setTimeout(()=>finish(),1000)}update()},1000)}
function update(){let el=$('#score');if(!el)return;el.textContent=S.score;$('#time').textContent=S.game==='hoops'?S.remaining:S.balls;$('#third').textContent=S.game==='hoops'?S.streak:(S.best.skee||0);$('#power').style.width=(S.power*100)+'%'}
function showGameError(message){S.running=false;clearInterval(clockInterval);cancelAnimationFrame(raf);const stage=$('.stage');if(!stage)return;let overlay=$('#game-error');if(!overlay){overlay=document.createElement('div');overlay.id='game-error';overlay.setAttribute('role','alert');overlay.style.cssText='position:absolute;inset:0;background:#171717ed;color:#f5f0e6;display:flex;align-items:center;justify-content:center;flex-direction:column;gap:16px;text-align:center;padding:24px;z-index:10;font:600 16px DM Sans';stage.append(overlay)}overlay.replaceChildren();const h=document.createElement('h2');h.textContent='GAME PAUSED — GRAPHICS ERROR';const p=document.createElement('p');p.textContent=message;const b=document.createElement('button');b.textContent='BACK TO GAMES';b.style.cssText='padding:12px 24px;background:#f5f0e6;color:#171717;border:0;cursor:pointer';b.onclick=()=>nav('select');overlay.append(h,p,b)}
function draw(now){if(!S.running)return;let dt=Math.min((now-last)/1000,.06);last=now;if(!S.paused){try{if(world3d?.error)throw world3d.error;world3d?.update(dt,S.aim,S.power,G.phase==='holding'&&S.mode==='camera',G.hold);update()}catch(err){console.error('3D game frame failed:',err);showGameError('The 3D engine stopped: '+err.message);return}}raf=requestAnimationFrame(draw)}
function renderStage(dt){const w=1000,h=562;ctx.clearRect(0,0,w,h);const bg=ctx.createLinearGradient(0,0,0,h);bg.addColorStop(0,S.game==='hoops'?'#152333':'#1d4e59');bg.addColorStop(1,S.game==='hoops'?'#4b2926':'#98734c');ctx.fillStyle=bg;ctx.fillRect(0,0,w,h);if(S.game==='hoops')renderHoops();else renderSkee();for(let i=shots.length-1;i>=0;i--){const b=shots[i];b.age+=dt;b.px=b.x;b.py=b.y;b.vy+=b.gravity*dt;b.x+=b.vx*dt;b.y+=b.vy*dt;if(S.game==='hoops'){if(!b.hit&&b.py<230&&b.y>=230&&b.vy>0&&Math.abs(b.x-500)<47){b.hit=true}if(b.y>174&&b.y<225&&b.x>421&&b.x<430){b.vx=Math.abs(b.vx)*.65;b.wall=true;tone(190)}if(b.y>475||b.x<20||b.x>980||b.age>b.maxAge){resolve(b);shots.splice(i,1)}}else{if(b.y<240&&b.vy<0){const zones=[[365,115,100],[635,115,100],[500,113,50],[500,155,40],[500,201,30],[430,205,20],[570,205,20]];let closest=zones.map(([x,y,p])=>({d:Math.hypot(b.x-x,b.y-y),p})).sort((a,b)=>a.d-b.d)[0];b.hit=closest.d<65?closest.p:0;resolve(b);shots.splice(i,1)}else if(b.age>b.maxAge||b.x<130||b.x>870){resolve(b);shots.splice(i,1)}}drawBall(b.x,b.y,b.radius,S.game==='hoops');}const cursor=G.phase==='holding'&&S.mode==='camera'&&S.tracking?G.hold:null;if(cursor){ctx.save();ctx.strokeStyle='#f5f0e6';ctx.lineWidth=3;ctx.beginPath();ctx.arc(cursor.x,cursor.y,35,0,Math.PI*2);ctx.stroke();drawBall(cursor.x,cursor.y,22,S.game==='hoops');ctx.fillStyle='#fff';ctx.font='bold 14px DM Sans';ctx.textAlign='center';ctx.fillText('RELEASE TO THROW',cursor.x,cursor.y-49);ctx.restore()}else if(G.phase!=='cooldown'||S.mode==='manual'){const x=100+S.aim*800;ctx.strokeStyle='#f5f0e6a0';ctx.setLineDash([6,8]);ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(x,505);ctx.lineTo(500,232);ctx.stroke();ctx.setLineDash([]);drawBall(x,505,21,S.game==='hoops')}ctx.fillStyle='#fff2d8';ctx.font='bold 16px DM Sans';ctx.textAlign='center';ctx.fillText(S.result,500,45)}
function drawBall(x,y,r,basketball){ctx.save();ctx.shadowColor='#0007';ctx.shadowBlur=9;ctx.shadowOffsetY=5;ctx.fillStyle=basketball?'#f1853e':'#f2e8d5';ctx.strokeStyle=basketball?'#492c25':'#6c737d';ctx.lineWidth=3;ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.fill();ctx.stroke();if(basketball){ctx.beginPath();ctx.moveTo(x-r,y);ctx.lineTo(x+r,y);ctx.moveTo(x,y-r);ctx.lineTo(x,y+r);ctx.stroke()}ctx.restore()}

function renderHoops(){ctx.fillStyle='#74494b';ctx.fillRect(0,470,1000,92);ctx.strokeStyle='#e4a76d';ctx.lineWidth=6;ctx.beginPath();ctx.moveTo(0,470);ctx.lineTo(1000,470);ctx.stroke();ctx.fillStyle='#f7e8c6';ctx.fillRect(420,110,160,120);ctx.strokeStyle='#aa463c';ctx.lineWidth=12;ctx.strokeRect(420,110,160,120);ctx.strokeStyle='#f3a15b';ctx.lineWidth=12;ctx.beginPath();ctx.ellipse(500,234,65,17,0,0,Math.PI*2);ctx.stroke();ctx.strokeStyle='#e2cab5';ctx.lineWidth=2;for(let i=-4;i<=4;i++){ctx.beginPath();ctx.moveTo(500+i*13,249);ctx.lineTo(500+i*10,318);ctx.stroke()}ctx.fillStyle='#c99d61';ctx.font='bold 18px "DM Sans"';ctx.textAlign='center';ctx.fillText('SWISH FOR +3',500,92)}
function renderSkee(){ctx.fillStyle='#8b4738';ctx.beginPath();ctx.moveTo(200,562);ctx.lineTo(320,190);ctx.lineTo(680,190);ctx.lineTo(800,562);ctx.closePath();ctx.fill();ctx.strokeStyle='#d7a96a';ctx.lineWidth=13;ctx.stroke();ctx.fillStyle='#402835';ctx.fillRect(283,80,434,165);let zones=[[365,115,100],[635,115,100],[500,113,50],[500,155,40],[500,201,30],[430,205,20],[570,205,20]];zones.forEach(([x,y,p])=>{ctx.fillStyle=p===100?'#f0bf56':'#f1dcad';ctx.beginPath();ctx.arc(x,y,p===100?29:24,0,7);ctx.fill();ctx.fillStyle='#542c2e';ctx.beginPath();ctx.arc(x,y,p===100?23:19,0,7);ctx.fill();ctx.fillStyle='#ffe9b5';ctx.font='bold 18px "DM Sans"';ctx.textAlign='center';ctx.fillText(p,x,y+6)});ctx.fillStyle='#ffdfad';ctx.font='bold 19px "DM Sans"';ctx.textAlign='center';ctx.fillText('CHOOSE YOUR ANGLE',500,52)}
function shoot(input={}){if(!S.running||S.paused||(S.game==='hoops'&&S.remaining<=0)||(S.game==='skee'&&S.balls<=0))return;if(!world3d?.launch(S.aim,S.power,input)){S.result='PHYSICS LOADING · TRY AGAIN';return}S.shots++;if(S.game==='skee')S.balls--;S.result='BALL IN PLAY';tone(300);update()}

function resolve(s){if(s.scored)return;s.scored=true;if(S.game==='hoops'){if(s.hit){const swish=!s.wall;S.streak++;S.longest=Math.max(S.longest,S.streak);const pts=(swish?3:2)*(S.streak>=3?2:1);S.score+=pts;S.hits++;S.result=(swish?'SWISH':'BUCKET')+' +'+pts;tone(790)}else{S.streak=0;S.result='MISSED · TRY AGAIN';tone(190)}}else{const pts=typeof s.hit==='number'?s.hit:0;S.score+=pts;if(pts)S.hits++;S.result=pts?'+'+pts+' POINTS':'MISSED · NEXT BALL';tone(pts>=50?780:420);if(S.balls===0)setTimeout(finish,2100)}update()}

function finish(){if(S.screen!=='game')return;stopGame();let prev=S.best[S.game]||0;S.newBest=S.score>prev;if(S.newBest){S.best[S.game]=S.score;localStorage.setItem('arcade-best-v1',JSON.stringify(S.best))}stopCamera();nav('results')}
function results(){app.className='page page-results';let accuracy=S.shots?Math.round(S.hits/S.shots*100):0;app.innerHTML='<section class="results-layout"><span class="overline">ROUND COMPLETE</span><h1>YOUR SCORE</h1><div class="score-ticket"><div class="ticket-avatar">A.</div><div class="ticket-text"><strong>'+(S.game==='hoops'?'BASKETBALL':'SKEE-BALL')+'</strong><small>SCORE</small><div class="ticket-number">'+S.score+'</div></div><div class="ticket-barcode"></div><div class="ticket-best">'+(S.newBest?'NEW PERSONAL BEST!':'PERSONAL BEST: '+(S.best[S.game]||0))+'</div></div><div class="result-stats"><div><span>ATTEMPTS</span><strong>'+S.shots+'</strong></div><div><span>SUCCESSFUL</span><strong>'+S.hits+'</strong></div><div><span>ACCURACY</span><strong>'+accuracy+'%</strong></div><div><span>'+(S.game==='hoops'?'BEST STREAK':'BALLS USED')+'</span><strong>'+(S.game==='hoops'?S.longest:S.shots)+'</strong></div></div><div class="result-actions"><button class="dark-button" id="again">PLAY AGAIN</button><button class="outline-button" id="change">BACK TO LOBBY</button><button class="outline-button" id="share">SHARE SCORE</button></div></section>';$('#again').onclick=()=>nav('mode');$('#change').onclick=()=>nav('lobby');$('#share').onclick=async()=>{let msg='I scored '+S.score+' in '+(S.game==='hoops'?'Basketball':'Skee-ball')+' on ARCADE.exe';try{if(navigator.share)await navigator.share({title:'ARCADE.exe',text:msg,url:location.href});else{await navigator.clipboard.writeText(msg+' '+location.href);alert('Score copied')}}catch(e){}}}

function pause(){S.paused=!S.paused;$('#pause').textContent=S.paused?'<svg viewBox="0 0 100 100" class="arcade-icon tiny"><path d="M25 10v80l65-40Z" fill="#ffe1a1"/></svg> RESUME':'<svg viewBox="0 0 100 100" class="arcade-icon tiny"><rect x="24" y="18" width="18" height="64" fill="#ffe1a1"/><rect x="58" y="18" width="18" height="64" fill="#ffe1a1"/></svg> PAUSE';$('#gamehint').textContent=S.paused?'GAME PAUSED':'Aim with your pointer • click or Space to throw • P to pause'}
function openSettings(){let d=document.createElement('div');d.className='modal-bg';d.innerHTML='<section class="editorial-modal"><button id="done" class="modal-close">← BACK</button><h1>SETTINGS</h1><h3>AUDIO</h3><label>Sound effects <input type="range" min="0" max="1" step="1" id="sound" value="'+(settings.sound?1:0)+'"></label><h3>GAMEPLAY</h3><label>Input sensitivity <input type="range" min=".5" max="1.8" step=".1" id="sens" value="'+settings.sensitivity+'"></label><h3>VISUAL</h3><label>Reduced motion <input type="checkbox" id="reduced"></label></section>';document.body.append(d);d.querySelector('#sound').oninput=e=>settings.sound=+e.target.value>0;d.querySelector('#sens').oninput=e=>settings.sensitivity=+e.target.value;d.querySelector('#done').onclick=()=>d.remove();d.onclick=e=>{if(e.target===d)d.remove()}}

$('#home').onclick=()=>nav('lobby');$('#settings').onclick=openSettings;$('#help').onclick=()=>alert('Pick a game, choose webcam or mouse, aim using your hand or pointer, then pinch-release or click/Space to throw. P pauses the round.');
document.addEventListener('keydown',e=>{if(e.code==='Escape'&&S.screen==='game')pause();if(e.code==='KeyP'&&S.screen==='game')pause();if(e.code==='Space'&&S.screen==='game'){e.preventDefault();shoot()}if(S.screen==='game'&&!S.paused){if(e.code==='ArrowLeft')S.aim=Math.max(.05,S.aim-.045*settings.sensitivity);if(e.code==='ArrowRight')S.aim=Math.min(.95,S.aim+.045*settings.sensitivity);if(e.code==='ArrowUp')S.power=Math.min(.95,S.power+.05*settings.sensitivity);if(e.code==='ArrowDown')S.power=Math.max(.15,S.power-.05*settings.sensitivity)}});
document.addEventListener('visibilitychange',()=>{if(document.hidden&&S.screen==='game'&&!S.paused)pause()});window.addEventListener('beforeunload',stopCamera);render();
